# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
# Inserts a blank line between shell prompts
add_newline = false
right_format = '$cmd_duration'
format = '$python$directory$git_branch$git_status$character'

[character]
success_symbol = '[](green)'
error_symbol = '[](red)'
vimcmd_symbol = '[](yellow)'

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
read_only = "󰌾"
truncation_length = 1
style = "blue"

[cmd_duration]
format = ' [$duration](bold yellow)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = ""
style = 'purple'

[git_status]
style = 'red'

[python]
symbol = " "
style = 'white'
format = '[(\($virtualenv\))]($style)'

