[font]
normal.family = "Source Code Pro"
size = 9

[cursor]
style = { shape = "Block", blinking = "On" }

[keyboard]
bindings = [

  { key = "k", mods = "Control|Shift", action = "ScrollHalfPageUp" },
  { key = "j", mods = "Control|Shift", action = "ScrollHalfPageDown" },
]

[window]
dynamic_padding = true
padding = { x = 5, y = 5 }
opacity = 1

[colors.normal]
black = "#080808"
red = "#984936"
green = "#789978"
yellow = "#ab8550"
blue = "#708090"
magenta = "#AA759F"
cyan = "#88afa2"
white = "#cdcdcd"

[colors.bright]
black = "#515151"
red = "#984936"
green = "#789978"
yellow = "#ab8550"
blue = "#708090"
magenta = "#AA759F"
cyan = "#88afa2"
white = "#cdcdcd"

[colors.dim]
black = "#151515"
red = "#984936"
green = "#789978"
yellow = "#ab8550"
blue = "#708090"
magenta = "#AA759F"
cyan = "#88afa2"
white = "#cdcdcd"

[colors.primary]
background = "#080808"
foreground = "#cdcdcd"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

