# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
# Inserts a blank line between shell prompts
add_newline = false
right_format = '$git_branch$git_status$cmd_duration'
format = '$directory$python$golang$rust$node$lua$character'

[character]
success_symbol = '[](green)'
error_symbol = '[](red)'
vimcmd_symbol = '[](yellow)'

[directory]
read_only = " 󰌾"
truncation_length = 1
style = "bold blue"

[cmd_duration]
format = ' [$duration](bold yellow)'

[git_branch]
format = '[$branch(:$remote_branch)]($style)'

[git_status]
format = '([$all_status]($style))'

[docker_context]
symbol = " "

[golang]
symbol = " "

[lua]
symbol = " "
format = 'via [$symbol(${version})]($style) '

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "
