# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# # Prompt
format = '''
[┌─╼](bold green)[\[](bold green) $directory$rust$nodejs$c$python$lua$golang[\]](bold green)$git_branch $cmd_duration
$character'''

# ~/.config/starship.toml

[character]
success_symbol = '[└─────╼](bold green)'
error_symbol = '[└─────╼](bold red)'
vimcmd_symbol = '[└─────](bold green)'

[directory]
read_only = " "
truncation_length = 3
truncation_symbol = '…/'
style="bold blue"


[git_branch]
format = '[──────\( ](bold green)on [$symbol$branch(:$remote_branch)]($style)[ \)](bold green)'

[docker_context]
symbol = " "


[golang]
symbol = " "

[hg_branch]
symbol = " "

[lua]
symbol = " "
format = 'via [$symbol(${version})]($style) '

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "
